### ISSUE TITLE
Plate Map Katherine Feedback

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#1031]
REQUIREMENTS:
Search form to narrow down plates by field in well - assigned compound in well, or SGC ID. Extra column on plate list table should show which well(s) contain that search hit.

When a compound is assigned to a well, structure should be shown if available.

Enhancements:
1. Export simple excel file showing mapped assigned compound to wells for a single plate.
2. Search by structure
3. Assign internal SGC Global ID - this is a project field on a batch, so "UOX" ID field could be autopopulated by that assignment.

**Comment by KarenPorter** [comment]
closing #1016.  substance of that was:

"notwithstanding the second part of this requirement (heatmap) - is it a minimum requirement to be able to retrieve a plate / well containing a specific compound?  I don't think that's possible."

It could be made possible because we are already using a modified version of the search interface to get the plate list. Could add a form which allows narrowing down of plates containing that cmpd.

Add a hoverover on the wells to see at-a-glance what they contain.

Add a column to the table when searching for a compound that displays which well contains that cmpd

Simple search form to examine other fields for data? Conc etc - can use the chembiohub search API for that (in some way)

**Comment by KarenPorter** [comment]
There's a large degree of overlap between these, so let's record in one issue..  Closing 1016

**Comment by PaulBarrett79** [comment]
Compound search:
I have included a uuid search form element within the plate list form.
Tried multiple methods of making this find plates containing the compound:
The documented way of generating a keyword search, speciying custom_fields.wells as the field - din't work.
Tried following other examples of generating encoded_params from inside the code - these also didn't work.
Tried including as a general textsearch generated using searchurlparamsv2 - inconsistent success. Did narrow down the  plate list but not always for hits that I knew were there. Also, on selecting an item from the uuid dropdown, I then couldn't select another (possibly because the selected item is a string rather than an array)

Have committed progress so far - may be worth a 10 minute discussion when I get back. It's not far off working correctly.

**Comment by PaulBarrett79** [comment]
There is no clear way of obtaining an image from the uuid - is the process to look up a batch from this via the search API then get the single batch which contains the base64 encoded image string?

**Comment by PaulBarrett79** [comment]
From requirements:
User can narrow down plates in list by whether they contain a particular CBH ID, or by another field (This actually performs a general text search across all the fields so could relabel as such?)

Re-reading the requirements I have omitted adding a column to show which well contains the hit(s). I can add this relatively easily but is not there at the moment.

Assigning a compound to a well causes a preview thumbnail to be shown.

Enhancements added:
Assign internal SGC Global ID and autopopulate CBH ID - this is how Katherine's group would assign compounds, so I have set this as the way to do it here. I have set up the SGC Global ID field on the General Project. The field on the form for an individual well has a dropdown/typeahead just like in the search form.

**Comment by PaulBarrett79** [comment]
Work so far is deployed to staging/demo

**Comment by aekhendry** [comment]
Yes all robust and working according to Paul's last comment. I have a few suggestion
;

Move the SGC Global ID to first in the list. It doesn't make sense to fill in a field that auto-completes other fields last

For search to be useful it must tell you which well it finds hits in. If you have the time I'd really recommend getting that sorted.

Otherwise very good. Testing, chrome.

**Comment by PaulBarrett79** [comment]
Swapped around the global and CBH IDs into a logical order.

Added a column to the table that is shown when a search is performed. It displays a list of wells which trigger a hit for the search. Works for both CBH ID lookup and the SGC Global ID lookup.

Added to github and deployed to staging/demo

**Comment by aekhendry** [comment]
I think the Plate maps search is now broken. I begin typing in the SGC Oxford ID and I get nothing back. It does briefly flash up with something but disappears instantly.

Also note that the search bar says 'SGC Oxford ID' whereas the actual field in he form submission says 'SGC Global ID'. That threw me a bit

**Comment by PaulBarrett79** [comment]
Re point 1: This SGC Global ID box is currently a free text search. No-one from Katherine's group needs to look up by CBH ID. So what I will do is: 
replace the CBH lookup with a SGC Global ID lookup (because this will be more useful to Katherine's group and the SGC in general)
replace the Label on the "SGC Global ID" box with  "Text Search" (will examine any of the well fields)

I will leave the existing CBH ID lookup in the code by way of example, as future users may need to know how to include other field lookups, or use the CBH ID as their primary lookup.

**Comment by PaulBarrett79** [comment]
Fixed the issues listed, just merging with recent other changes.

**Comment by aekhendry** [comment]
Tested, looks good. Staging/demo chrome
