### ISSUE TITLE
Multiple Batch ID' is used as a search criterion but the user has no idea what it relates to.

I don

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#284]
Multiple Batch ID' is used as a search criterion but the user has no idea what it relates to.

I don't think the batch ID is returned to the user when they update a batch of compounds (that I can recall seeing) so they wouldn't be able to refer to it later.  I can see the value of this when linking from the user's list of batch uploads - just that it isn't obvious directly from the search page.  Maybe an info icon next to the field to explain what it's for?

**Comment by PaulBarrett79** [comment]
I had to put this in the search form in order to allow displaying compounds per multiple batch from a link in the user page. It might be that we have this display slightly differently - rather than the id itself, some metadata in the form of a tag? For example a tag field saying "Upload by user_id on date"?

**Comment by strets123** [comment]
rename to upload id for now

**Comment by PaulBarrett79** [comment]
Renamed to Upload ID. Now on sandbox.

**Comment by KarenPorter** [comment]
Upload ID label in search parameters but the results table has a label of Batch ID still so there's an inconsistency.

**Comment by aekhendry** [comment]
Karens issue still exists?

**Comment by strets123** [comment]
No the batch ID is now the batch id
The upload ID is labelled accordingly

**Comment by KarenPorter** [comment]
fixed - passed test
