### ISSUE TITLE
Feedback on UI for registration

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#354]
I am working on the UI for registering a compound to simplify the process and give more of a clue what is going on as you do it. I am also aiming to use the screen space more effectively.

The home icon top right will now point back to the project home page.

Any feedback or questions is welcome. @nroam @abradle @aekhendry @KarenPorter @ddamerell53 @PaulBarrett79 

https://drive.google.com/file/d/0B7C1B_NpgEHQUXplSG5TdmtXbW8/view

There will be a pageable table view showing the uploaded data with a buttons for 

* mark column as structure column
* ignore column
* and a dropdown to select the column that this column in your data should be mapped to.

The stats in the top left will allow filtering and there will be a select all workflow with tickboxes to save compounds.

The progress bar and the fraction in the top right will show how many of the compounds have been dealt with.

**Comment by KarenPorter** [comment]
I think it should be more obvious what project the user is currently in (eg in header – could this be with dynamic project home label, so ‘Project DND home’?).

Good that the primary upload method is centred – user’s eye falls immediately to that.  It could be further emphasised relative to the draw option (minority method), for example by having a darker grey box around it.

Could the drag / drop and paste option be on one tab with the doodle on  a second?  Default is first tab.  Needs a process button so if that’s underneath (right aligned with paste box), the tab button could be to the left of the process button.

The stats are a nice feature where they are but I’m not sure they would be instinctively recognised as filter buttons (too far away from the site of action and also look like they’re for information rather than action).  Perhaps repeat at the top of the table view – introduce with a ‘Filter’ label, make smaller, replicate colour and use an icon. Then user would see after first use that they are replicates.  And repeat at the bottom of table view (including ‘save these compounds’ button).

Table view sounds ok – would be good to see that.

K

**Comment by aekhendry** [comment]
Looks great! I think we need to emphasize a help option for new users on pages like this. A very obvious link that takes you to a demo video would be ideal. Outside the scope of this example, it would be great if we could have a system where first time users are asked whether they want to view a quick 'introduction to ChemReg' video. Bare in mind, any help document needs to be take into account our two user groups - those registering compounds and those searching for compounds. I'm starting to find that people who aren't chemists are a little intimidated by chemreg. We need to make them feel more comfortable if we can.

**Comment by strets123** [comment]
I have added a new version here:

https://drive.google.com/file/d/0B7C1B_NpgEHQYktZZ3RsUGJ1eW8/view?usp=sharing

I have added buttons and heading and separated the single molecule into its own tab.

Intention is that there wont be a button to process data, you just add it in and it will process after every change.

Let me know if you would prefer this to be done the old school way...

**Comment by KarenPorter** [comment]
I *really* like that – simple, unfussy, intuitive.

I’d even  suggest tweaking to say “Drag and drop your files here” – with an (i) to list the file types that are acceptable  -that way it is extensible, and the error message for invalid file types can reiterate file types that can be processed.

K

**Comment by strets123** [comment]
Yes, makes sense, I have made that change.

**Comment by strets123** [comment]
This was more of a pre feedback thing
