### ISSUE TITLE
Search should allow user to define relevant Boolean operations (currently only OR I believe).

And m

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#355]
Search should allow user to define relevant Boolean operations (currently only OR I believe).

And maybe at some point provide a 'superuser' interface to write more complex parameter combinations which would parse straight into URL?

**Comment by strets123** [comment]
I don't agree - too complex. We should just default to the excel style filter - OR if within a column, AND if between columns. We can then have excludes. If people want 2 separate queries combined that could be added at a later stage.

**Comment by nroam** [comment]
Key mantra: KISS (for now).

**Comment by PaulBarrett79** [comment]
To that end I have altered the search query so that searches within custom fields are OR within the same field and AND between fields.

It is likely that we will allow specification of AND/OR according to the user's wishes but this is a more sensible and expected default.

Pushed to Github, awaiting sandbox deployment.

**Comment by PaulBarrett79** [comment]
Deployed to sandbox

**Comment by KarenPorter** [comment]
tested -passed
