### ISSUE TITLE
inventory manager needs a proper name

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#366]
Can we have some suggestions for what we call the chemreg inventory manager? Bare in mind that it will not just be used for reagents, it can also store plasmid / antibody / cell line info etc and so needs a catch all name if possible. It also needs to be consistent with the ChemReg name if possible.

Some examples:
ChemBio Inventory
ChemInventory
ChemBio Tracker
ChemTracker
ChemSpotter
ChemHunter
ChemLocater
ChemFinder - too similar to another product
Chemfindyourstuff.com

Feel free to comment

**Comment by PaulBarrett79** [comment]
There's a trello item where we tried coming up with names for this, including some we categorically ruled out - I'll find it and put the names up here

**Comment by PaulBarrett79** [comment]
https://trello.com/c/xkyxwnfq/29-naming

Some of these we ruled out using as the name for Reg because they were too "inventory" for what ChemReg has become  - so maybe some ideas there?

Reg
Shelf
Rack
Base
Pod
Depo
Depot - a set of silos
Chembio CAB - let's you register compounds, assays and biomolecules
Caddy
Bucket
checkin
bay
dock
hold
stack
store
space
hold
holdzone
locate
link

**Comment by aekhendry** [comment]
I like ChemStore?

**Comment by strets123** [comment]
We are in danger of having too many brands

**Comment by strets123** [comment]
InvReg is the name now, marking as done
