### ISSUE TITLE
Non-SSO doesn't provide error message for invalid credentials.

I put the wrong password in - and go

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#369]
Non-SSO doesn't provide error message for invalid credentials.

I put the wrong password in - and got the login page without the user name and password fields.  

Sandbox instance.

**Comment by strets123** [comment]
Easy fix and required now we have people from outside with logins

**Comment by PaulBarrett79** [comment]
Can we please ban the use of "easy fix"...

**Comment by strets123** [comment]
I have deployed the fix for this. This will also enable password login for webauth instances (for test purposes) I am not sure how this will look until we deploy to webauth.

**Comment by KarenPorter** [comment]
Testing in TagNew.  From /login page - type in invalid password.  Get error message and my saved password is reinstated so that when I hit 'sign in' I do log in. 

I then hit 'back' and get - 

Forbidden (403) CSRF verification failed. Request aborted.
Help
Reason given for failure:
    CSRF token missing or incorrect.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:
Your browser is accepting cookies.
The view function uses RequestContext for the template, instead of Context.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.
You can customize this page using the CSRF_FAILURE_VIEW setting.

**Comment by KarenPorter** [comment]
Sorry, not quite accurate - I hit back and get to the login page again, when I put in erroneous credentials I get this error message.

**Comment by strets123** [comment]
OK, weird issue was causded by the way browser does the back. Anyway I have found a workaround I believe, please test in tagnew

**Comment by KarenPorter** [comment]
If I'm logged in and go back to the login page (browser back), regardless of the credentials I put in, I get into the application as the already logged in user.  Instead - if I go back to the login page and I am already logged in, I should get the message something like ' you are logged in as xxxx', click here to log out.  the standard login userid/ password fields are then shown to allow me to login with new credentials (or the same ones)

**Comment by strets123** [comment]
Re tested by Karen and passed
