### ISSUE TITLE
Functional Requirement - Inv.
User can add a single entry for a compound directly into their invento

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#439]
Functional Requirement - Inv.
User can add a single entry for a compound directly into their inventory project (without Excel intermediary). With validated field options.

**Comment by KarenPorter** [comment]
Proposed approach:

1 add new compound from scratch
from project list or search, select 'add single compound' which takes user to add compound page.
Select appropriate project (whicg defines project data fields)
variation of the compound detail form is used to validate data
user can preview, then commit (or cancel / return).

2  clone from existing
from search results or project list, user selects  clone option from grid view which takes user to add compound page, with relevant fields all complete
completion as above.

**Comment by PaulBarrett79** [comment]
User can now add a single item via the project summary page for non-chemical projects.

To test, you have to have a non-chemical project. I will add steps to test once the migration is there.

Pushed to github

**Comment by KarenPorter** [comment]
1.  Data entry fields aren't aligned (offset by the Project Data Summary button)

2. "Clear form" doesn't clear invalid numeric defined fields

3. First numeric field I put alpha text in - get red X (but doesn't clear - per item 2), subsequent numeric fields i put alpha in - doesn't accept text and validates with green tick.

4.  Tabbing proceeds column-wise rather than row-wise (I'd expect row-wise)

5. Wrote the record even though I had 2 red Xs (surely they should prevent proceeding until resolved?)

6. "Clear Form" and "Save record" buttons move around depending on number of custom fields.  Karen Test now has 7 so these 2 buttons are placed mid-column on the rhs.

**Comment by strets123** [comment]
6) Is this not normal for a multi-column form?

**Comment by PaulBarrett79** [comment]
Re. point 4 - I think up/down tabbing is acceptable, and opinion on this will change from user to user. As long as the tabbing experience is consistent, this is all that we can do.

**Comment by PaulBarrett79** [comment]
Points 1 and 6 fixed.

**Comment by PaulBarrett79** [comment]
Validation in angular schema form (the library we are using to render our forms) is basically broken. Therefore I have disabled client side validation for this section of the app. The numerical fields prevent text entry and dates and text are handled fine.

This will need revisiting but for now, since we cannot rely on angular schema form to give consistent validation feedback results, we cannot use that aspect of the functionality.

**Comment by PaulBarrett79** [comment]
All these issues are now handled - pushing to github, awaiting deployment to sandbox

**Comment by PaulBarrett79** [comment]
Deployed to sandbox
