### ISSUE TITLE
Functional Requirement - Inv.
User can download an Excel template which defines the relevant custom 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#443]
Functional Requirement - Inv.
User can download an Excel template which defines the relevant custom fields for the given project.This will then help them populate data in a relevant way so that when they upload it it is more likely to automap and pass data validation checks.

**Comment by PaulBarrett79** [comment]
User can now download a summary excel file of the pinned custom fields (Project Data as presented to the user) from the project list summary. This file contains the data type for each field, allowed values for multiple select fields and the help text for each field where supplied.

Pushed to github, waiting for sandbox deployment.

For the record this took 5 hours rather than 1

**Comment by KarenPorter** [comment]
Not exactly what I had in mind- user can't just use this to populate their data.  It has one row per custom field in definition whereas I was envisioning the appropriate custom field names as column headings.  What's there is nice in that it provides more information and I think should be kept but should also include an actual Excel template of a valid format.

perhaps put the transposed column A values on one sheet and the definition on another sheet?

**Comment by PaulBarrett79** [comment]
This has been discussed and decided that this comment forms new  or enhanced functionality and will be moved to a new issue.

The original spec for this issue has been fulfilled and as such will be moved to Testing.

**Comment by PaulBarrett79** [comment]
Added #490

**Comment by KarenPorter** [comment]
Passed testing.
