### ISSUE TITLE
Table does not allow fill down on array fields

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#492]
This bug with handsontable was added to the sprint to enable the update functionality to work in full. It was not foreseeable.

**Comment by strets123** [comment]
Fix implemented but will need more work to make it something that we can submit as a patch to handsontable.

**Comment by KarenPorter** [comment]
Passed the substantive functional test.

2 remaining issues (which I'm happy to have reflected as a new issue if appropriate):

When I select multiple cells in a row, the table jumps back to the left and I can't select further cells to the right (will not scroll without losing my selected cells),  so I'm limited in the number of cells I can select in order to drag down .

When I select cells with blank values and drag to fill over other rows, it doesn't blank out any choice- or tag-field cells (they remain with the values previously selected).

See me to demo if this isn't clear(!)

**Comment by strets123** [comment]
First issue will have to be worked around by zooming out for now.

**Comment by strets123** [comment]
Second issue is a separate bug - it is also possible to work around this one but you must explicitly save the cell you are copoying from as a blank cell.

It has previously been a non existant attribute on the json object. 

There is a task to decide how we want to handle field defaults in assay reg.

**Comment by KarenPorter** [comment]
new issues raised.

Original issue passed testing.
