### ISSUE TITLE
File upload unmapped field warning pop-up required

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#544]
When a user uses the system, the one thing they must learn is to map their fields if they differ from what's there. Currently there is no warning that you are submitting an unmapped field on file submission, and no explanation as to why this is so important. I really think this should be there as this is the only part of the system that is sometimes difficult to convey and I really want to avoid any incidents with unmapped fields later on down the line.

**Comment by aekhendry** [comment]
I appreciate this wasn't discussed before, but I think this would require very little effort and would make the upload process rock steady in terms of user understanding. Happy to be told otherwise.

**Comment by PaulBarrett79** [comment]
I have added functionality which:

1) Displays a message above the preview table indicating that there are mandatory unmapped fields in their file - when the file is uploaded, automapping of fields is attempted.
2) The mapping icon on each column indicates that there is a mapping issue or no mapping (yellow) or column is mapped (green)
3) On opening the mapping popup, a message is displayed if the attempted mapping is not possible.
4) Rows causing the mapping issue, due to data type clashes, are displayed in a table in the popup
5) User cannot save their uploaded file if all mandatory fields are not mapped.

This is deployed to tagnew instance.

**Comment by KarenPorter** [comment]
awaiting Andy's error testing

**Comment by strets123** [comment]
Now tested, bugfixes applied

**Comment by KarenPorter** [comment]
See feedback in issue 579 for defects.

**Comment by PaulBarrett79** [comment]
#579 is now in proposed for November so... What do we do here?

**Comment by KarenPorter** [comment]
If there are elements of #579 which have been addressed in Oct - provide an update in this issue and update #579 to reflect what is outstanding (or break out into separate issues if appropriate).

**Comment by aekhendry** [comment]
Tested marked as fixed

**Comment by aekhendry** [comment]
Tested marked as fixed
