### ISSUE TITLE
Search needs improvement on ChemReg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#592]
• Search – Auto complete option should not be only search item returned. i.e. you search ‘plates’ should bring back all entries that contain the search term ‘plates’.

**Comment by PaulBarrett79** [comment]
Search integration for ChemReg search

**Comment by strets123** [comment]
For the requirement of making the custom field search work in ChemReg, we need to make the following things work:

1) Search in the toolbar with an autocomplete to show number of batches matched by project
2) Instant search without having to click search with a search bar at the top of the table like on assayreg (content at bottom should change and URL should change without having to click search)
3) Custom field search with an "add a field" button like we were going to do on assayreg.

In order to have one codebase between assayreg and chemreg, we also need to:
Fix issue with substructure search when no record is found

**Comment by strets123** [comment]
Part C is not done but other parts are done

**Comment by KarenPorter** [comment]
How do you want to deal with this then?  Move forward for test and sign-off and add a new issue for part C? @strets123.  It's in backlog at the moment but only part C is potential backlog.

**Comment by strets123** [comment]
Yes, let's create a backlog item for part C

**Comment by KarenPorter** [comment]
part B completed but others are outstanding - send to backlog

**Comment by strets123** [comment]
You can now do prefix queries via the search box on ChemirReg, closing
