### ISSUE TITLE
rows are not in the same order as they were in the file. assayreg tagnew

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#616]
• I upload a file into assay reg and save. Data is represented fine, but all the rows are not in the same order as they were in the file. They really need to be, from a user standpoint this would be very irritating.

**Comment by PaulBarrett79** [comment]
Now then, there is a logic issue here.

We want the most recently added items shown first when saved. If we are saving in the order in the file, then the last record will be first, and vice versa. The most recently added item will be the last row in the file, so this will be shown first.

The preview table DOES show rows in the correct order, replicating what is in the file - if this is not the case in tagnew, I cannot replicate it for a variety of different files

I propose that during the process of saving the files on the backend, when it is converted to a data frame, the order is somehow flipped so that records are added in reverse order. This means that records for one upload will be shown in the order of the file.

**Comment by PaulBarrett79** [comment]
Except that the items are added in an arbitrary order - we need to retain the order from the preview somewhere, then flip it during post_save_temp_data, then it will be in the file order.

**Comment by PaulBarrett79** [comment]
Items are now added in reverse order to how they are in the file, so showing as the correct order when shown in the data overview.

Pushed to github

**Comment by PaulBarrett79** [comment]
Awaiting deployment

**Comment by PaulBarrett79** [comment]
Deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
Tested - passed.  Closing issue
