### ISSUE TITLE
Excel compound uploaded in AssayReg, blinded compound are not being registered

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#627]
I upload an excel file in assayreg compound upload. The file has entries with and with out structure. The preview of the file shows that the blinded compounds are flagged as SMILES not processable :nan. Saveing the file results in all blinded compounds being ignored and not saved. The rest are saved as normal.

**Comment by aekhendry** [comment]
Example file sent to Andy and Paul

**Comment by strets123** [comment]
Uploading a mixed file like this is not a feature. As such this is a feature request not a bug. Same thing happens on hub.

**Comment by PaulBarrett79** [comment]
The real question is that, now that we have accounted for users being allowed to upload non-processable compounds as blinded, should we be marking ANY compounds as Ignore? 

Alternatively would it be better to have a checkbox somewhere at the top of the file preview  - something like "Ignore all unprocessable" or better wording - so that the user can decide whether to register stuff as blinded or not?

Is there a use case where any user will go through their records individually and mark them as ignore or not? Do we know of anyone doing this at the moment?

I think switching this blinding action on/off will be sufficient for 99% of users. "Load my stuff" or "Ignore everything that has a problem".

What does everyone think?

**Comment by KarenPorter** [comment]
agreed - let's raise at standup and confirm @paulbarrett79

**Comment by aekhendry** [comment]
I agree with your points Paul. I do however think that we should leave in the functionality to ignore an entry if you chose to do so. I feel that this might be something an experienced user might start playing with, and so I think it would be premature to take it out right now.

**Comment by strets123** [comment]
Discussion of the different possibilities for upload to be continued in #682.

**Comment by strets123** [comment]
@aekhendry for information please close

**Comment by aekhendry** [comment]
Closing
