### ISSUE TITLE
make it easier to see our applications from within the web pages, with more horizontal linking betwe

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#655]
make it easier to see our applications from within the web pages, with more horizontal linking between the application pages.
 
Specifically I’d like to link to /assayreg from the /chemreg and /inventoryreg pages; /chemreg from /assayreg and /inventoryreg; and /inventoryreg from /chemreg and /assayreg.
 
I would suggest (using the example of the /chemreg page), at the bottom of the ‘What’s the problem’ section adding “If you have an issue in managing assay data  or in keeping tabs on your lab inventory, check out our AssayReg and InventoryReg pages <hyperlinked>.  At the bottom of the “What is ChemBio Hub ChemReg” section, adding links to “You might also want to check out our other applications AssayReg and InventoryReg” <hyperlinked>.
 
Repeating with appropriate links on the/assayreg and /inventoryreg pages.
 
From the image at the top of the /applications page, we should include links to the relevant /xxxreg pages– so allowing ChemReg and the associated image to be clickable and linked to /chemreg (repeated for the other 2 applications).
 
The /assayreg page doesn’t have the ‘Back to top’ links that the other 2 pages have.

**Comment by KarenPorter** [comment]
Paul has made these changes - awaiting testing by KP

**Comment by KarenPorter** [comment]
/applications page - the click area around ChemReg and InventoryReg images aren't very well aligned, so possible to click on the images and for nothing to happen.

/chemreg page - the link to login at the bottom doesn't launch a new tab as the top link does (instead it navigates  away from chemreg to webauth).  The 'get in touch' button creates an email with subject of AssayReg Info instead of ChemReg info.  Missing 'Request a demo' button (as in inventoryreg page) with relevant text in email link.

/assayreg - typo "check outthe other".  Typo, missing "the" in  "data in context".  The link to login at the bottom doesn't launch a new tab and isn't the webauth link as it should be. There isn't a link to GitHub from the bottom of the page, as there is on chemreg page - would be good to be consistent.  Missing 'Request a demo' button (as in inventoryreg page) with relevant text in email link.

/inventoryreg.  Typo - " in keeping tabs on your lab inventory" - should be "managing chemical data" or similar.  Typo "update the compound information" - should be "update the inventory information".  The link to login at the bottom doesn't launch a new tab as the top link does.  Are the thumbnails for Upload compound and Mark individual records appropriate for InventoryReg - more relevant as they are to ChemReg surely?

@paulbarrett79

**Comment by PaulBarrett79** [comment]
Changes applied Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging.chembiohub.ox.ac.uk

**Comment by KarenPorter** [comment]
/applications - passed

/chemreg- text in the 'get in touch' and 'request a demo' buttons is squished / cropped, as are all bold words in text.

/asssayreg - still the wrong link at the bottom  (/login rather than /webauth).   Bold text odd (like /chemreg page)

/inventoryreg - the weird bold thing..

**Comment by PaulBarrett79** [comment]
Changes applied

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging.chembiohub.ox.ac.uk

**Comment by KarenPorter** [comment]
passed

**Comment by strets123** [comment]
deployed
