### ISSUE TITLE
Adding a file to assayreg/ invreg saves in reverse order to that shown in file

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#665]
Adding a file to assayreg/ invreg saves in reverse order to that shown in file. This is very annoying behaviour, when saved and in search the entries should be in the same order they were displayed in the file. This behaviour is different to that seen in assay reg which jumbles the rows up randomly.

**Comment by PaulBarrett79** [comment]
As I described in #616, this is because the results are ordered to show most recent first. As items are being added in the order they are shown in the file, this means that the most recent item is the final item in the file. I can do what I did for #616 and reverse the order they are added (by changing the sort order of the dataframe in this instance. They will then be shown in the order they were added but with more recent uploads first.

I am slightly uneasy about doing this as I think some people may argue the logic of doing it this way.

**Comment by PaulBarrett79** [comment]
Files display items in the order they were in the file after being saved to the system.

Load a file
Save
Items are shown in the same order as the file.

Pushed to github

**Comment by PaulBarrett79** [comment]
Awaiting deployment

**Comment by PaulBarrett79** [comment]
Deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
tested - works to agreed revised logic (and looks much better to end user)
