### ISSUE TITLE
in search activities, drop-downs don't close unless I select an entry or click in another drop-down.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#676]
in search activities, drop-downs don't close unless I select an entry or click in another drop-down.  if I click, for instance, in a date field the drop-down options remain.

I raised this before but might have been while waffle was misbehaving (apologies if it's a duplicate)

**Comment by KarenPorter** [comment]
and the list of users in the drop down is'nt alphabetically ordered - suspect it's in order of users added.  Needs to be alphabetised as default

**Comment by strets123** [comment]
What is the expected behaviour here? Everything I see is normal and consistent with this kind of UI - dropdown closes if I do any of the following things - 

click anywhere outside the dropdown
click another dropdown
delete all of my selections
press tab.

Clearly if I click on the dropdown in general it must not close as this is the action to open it. Issue rejected.

**Comment by KarenPorter** [comment]
If I click anywhere outside the dropdown - it doesn't close (unless I click in another dropdown).  This is not expected behaviour.  I expect the dropdown to close when I click elsewhere.  I'm using Chrome.

My point about the order of entries in each dropdown hasn't been addressed - they are all in order that they were added (I think - certainly nothing obviously logical).

**Comment by strets123** [comment]
This may happen but we are marking as wont fix because of the effort needed to investigate across different third party libraries
