### ISSUE TITLE
External sign in

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#679]
She also wants to sort out a way that the external collaborators can look at the compounds in the project. She would like them to be able to sign in via her portal and then have permission to login from there. Alternatively maybe she can have admin rights and assign users herself? Either way a system needs to be created for new users to login without webauth.

**Comment by strets123** [comment]
- [ ] Invite via standard front end given privileges to a specific project
- [ ] Generate a password and store it securely
- [ ] Password reset

**Comment by PaulBarrett79** [comment]
Invite work under way

**Comment by strets123** [comment]
Remaining tasks


Handle repeat invitations (would you like to invite them again? for now)
Add different templates for the invited user - emails and confirm and redirect them into the app when they have set password
Add the project permissions to the users
Handle webauth users
Set up the site setting for production
Document the process of setting this up
Ensure the email system works on production

**Comment by strets123** [comment]
Pushed to hubtest but need to complete permissions on this

**Comment by aekhendry** [comment]
Password Reset Successful
Your password has been successfully set. You may now log in with your new password.

The login link following password registration is broken. Also the page itself has not loaded fully. Is this part finished yet?

**Comment by strets123** [comment]
This is now ready to re test on the production server hub.

I have activated the email functionality and added the changes needed to the forms so that they redirect to the login page.

Remaining are these 2 issues:

https://github.com/thesgc/chembiohub_helpdesk/issues/762
https://github.com/thesgc/chembiohub_helpdesk/issues/761

These are left out of the scope for now.

I have also added a check to ensure the inviting user is an editor of the project.

Thanks,

**Comment by KarenPorter** [comment]
new defect raised #774 to capture that we can't send invitation to renamed projects - not a high in respect of signing off on this task.

**Comment by KarenPorter** [comment]
When I click through to password reset and from there to logon - the credentials used are for my admin account, rather than the non-webauth account I've just changed the password for.  May be an unlikely scenario but if an admin used someone's desktop to send them an invitation, then left them to change password and carry on accessing project information they could be inadvertently using the administrator's credentials.

**Comment by KarenPorter** [comment]
Improve UX in this scenario to include an email link in the last sentence so tat user can actually make the request:

                              Confirm Password Reset

                              You have requested to reset your password.

                               The password reset link was invalid, possibly because it has already been used. Please request a new password reset email.

**Comment by KarenPorter** [comment]
to the confirm password reset page when the link should be valid.  The scenario was tat I had the original email inviting me, plus a follow up email reminding me (I had sent an invitation to a second project before logging on).  I then clicked on this link https://chembiohub.ox.ac.uk/hub/login in the original invitation, which logged me on via webauth.  I then clicked the 'confirm registration' link in the invitation and got this message.

Apologies if this isn't clear - I can demo steps if that is easier.

**Comment by aekhendry** [comment]
There are a number of things here Karen has raised that have not been addressed as far as I can see?

**Comment by strets123** [comment]
Password reset link has been added to the confirm page in case of failure

**Comment by strets123** [comment]
I have also added a password reset link if there was an error submitting username and password

**Comment by aekhendry** [comment]
Working, hub chrome

**Comment by strets123** [comment]
Deployed
