### ISSUE TITLE
Clicking export data summary in file export options in search is broken

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#757]
takes you to here: https://chembiohub.ox.ac.uk/hub/api/cbh_projects/?project_key=&format=xlsx

Can we please disable this until it is fixed.

hub - chrome

**Comment by KarenPorter** [comment]
@strets123 duplicated - please consolidate all excel export outstanding issues into one and close the others

**Comment by strets123** [comment]
Now replaced with a button on the add compounds page as this is where this feature is needed

**Comment by KarenPorter** [comment]
this is hard to determine what the fix is.  However, when I look on the add compound page, there is an issue with the text, which says:

Drag and drop your files here download an Excel template from

So the text is wrong.  Am i supposed to be testing the downloaded template?  If so, that does look good - no issue seen in testing.

**Comment by strets123** [comment]
copy now fixed

**Comment by KarenPorter** [comment]
text is now correct on Firefox (where there's no previous caching).  

Trivially - there needs to be a gap between the button and the drag-and-drop area, currently bumping up against each other.

**Comment by strets123** [comment]
Now moved the message to below

**Comment by KarenPorter** [comment]
passed
