### ISSUE TITLE
Admin UI upgrade

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#784]

**Comment by strets123** [comment]
UX of admin tasks

Things that actual real people - in the real world - want to do:

User admin
	add user (can now do via invite) internal and external
	change user permissions
	change user groups
	change user access to projects
	Transfer User permissions from internal sign in to external sign in
	Ability to ‘donate’ permissions if leaving
	Ability to remove yourself from a project
	Remove user entirely

Project admin
	changeChange the name
	changeChange the custom fields - do we allow this? wouldWould have to convert existing ones to uncurated if any are removed  
	Change order of custom fields in table
	Create new project
	Aarchive projects

Group admin
	Ccreate groups
	Aadd users en-masse
	Edit group permissions
	


Single Record admin

	Add uncurated comments?
	Edit compound (already possible)
	deletion/archive (already possible)
	mass deletion (already possible, sort of)
	Restore from archive. 
	Roll back to previous version – preview previous version (when versioning has been implemented).

Self admin
	Personal details (if webauth or user creation details not quite correct)
	change email - external collab may change location and not take their email with them?  Tricky as email will be username.
	Leave system
	

Project setup
	add users to new project en masse and assign perms
	custom fields setup
	wording for assay levels
	chembl mappings - or is that the curator's job only? Can we give a list of preferred terms? 

The admin tasks that people would like to do can be grouped into:
User admin
Project admin
Project setup

General UX points to note
=========================
Aside from having intuitive forms - or failing that, clear instructions - for what the user may wish to do, it is really important to also include:
- sideways links across similar or related admin pages - so adding a new Project also side links to adding new groups and project types, for example.
- if something goes wrong, tell the user in sufficient detail as to help them. Avoiding jargon and error codes is also important. One approach is to include a "try again" button which may get around edge case errors like not waiting sufficient time for web services to load etc. This helps the user feel like they have a bit more control and that the system is accessible. Many sites use this approach for the "one in five" errors that may occur.


User admin
==========
Our example user for this task is Lara. Lara has a large group of students who are all, broadly speaking, on the same projects. She also has external collaborators which she would like to grant access to via an invitation.

The app already has a user list outside of the normal admin screens. Any permissions changes for an individual user can be linked to from here. This is user friendly and a sensible place to have such functionality.

I recommend changing the users list to something more like the new project list - full page width with a filtering bar at the top to aid with finding a specific user.

Within each user row, the facility to see which projects the user is assigned to and a link to add them to more (via a popup - same mechanism as adding projects to invited users currently) or change their permissions on the ones they can see. Being added to a project gives a user read permissions - after addition their permissions can be changed, consistent with the invite mechanism.

This would also be a convenient place for user metrics to be displayed (items added for example, or possibly even invites sent?)

Project setup
=============
Our example user for this task is Ines Barreiros (DPAG). Ines has a number of projects starting and needs to be able to initialise these as needed. Ines knows the project fields for some of her projects but not for others yet - the grant she is working on is at an early stage so some of the protocols are still being worked out.

We currently have a project list which is a convenient place to have links to set up new projects via a link at the top of the list.

Adding a project should allow the appropriate user to set it up without needing to have all the other necessary details supplied straight away, as a placeholder.

When the user is ready to add project fields (custom fields), they should be able to do so either by csv, excel or SD file (for a chemical project). Users will know what their fields are either from machine readouts or from existing project documents.

The system should be able to display all the fields found.  The user can then specify which of these they want to use, via a checkbox. Everything is selected by default. User can deselect if they wish.

If there is data present in the file, the datatype can be determined automatically. Would all users be realistically expected to do this off the bat? Would we allow users to input data with no datatype check? (make everything text/character based?)

Project administration (changing stuff)
======================
All project supervisors will need to change something about an existing project at some point. This definitely includes amending or adding to the project fields - for example a commonly used supplementary data field could be "upgraded" to make it searchable - and may in the future include archiving a project, or making it read-only by "closing" it to new submissions.

Again, we have an existing project list so admin actions for a project should be accessible via this list.

**Comment by strets123** [comment]
Permissions to be managed via the given project or in a list of projects like on github. To avoid making the features twice

**Comment by strets123** [comment]
#Implementation details:

**Comment by strets123** [comment]
=================
Organisation feature
-------------------------------
New API for organization, subclass of group
Ownership is persisted as permissions eg org1_owner
Membership is just the members of that django group
Owners list and members list is added to API as an attribute for the given organisation and db changes are dealt with on the backend by overriding default tastypie methods
Also a simple attribute like we have for project to say user is an owner
User can add the project to their organisation
Owners can invite people to an organisation which sends an invite
Owners can remove people from the organisation. 
Owners cannot leave the organisation - they have to ask some other owner to remove them having the effect that an org must have an owner
Owners can archive an organisation
Members can just leave an organisation
Based on the department affiliations, organizations will be created but they won't have owners until we assign them in the admin - they don't need owners


Invite feature changes
-------------------------
Existing user can invite new user using current functionality
Oxford users can be invited
Existing user can optionally add organisations to the invitation if they are the owner of that organisation
New User accepts invite
New User's Organisation group is generated with New user as owner and New user is added as a member to any organisations that were in the invitation
Permissions on existing projects and organisations are not managed by the invite feature, that is done via the organisation or project at hand

Project admin changes
---------------------------
 Owners of an organisation can change the name of a project in it - need to also fix the issue with names etc. against the permission codes
Email should be sent to all of the organisation and users of the project if the name is changed
Change order of custom fields in table and other views  (via scheme on project without telling user about that)
Hide custom fields (via scheme on project without telling user about that)
Add custom fields to project - note that other projects would not be enabled 
Create new project
Archive projects
Remove user from project if you own the organisation above the project and you are an editor
Give user editor permissions if you are an editor of that project

Custom Field Schemes
---------------------------
As with JIRA there comes a point when the custom field information needs to be properly rationalised so that schemas can be shared across as many projects as is feasible
There are 3 ways this could be done:
- have a template system for new objects similar to the copy and paste feature we had in old admin - this does not really promote sharing and there is no way to recommend new fields to other labs
- have move all fields to a central store and have only 1 definition per field name - this could work but it seems quite "heavy touch" on the functionality we already have in place and working
- Create "custom field scheme" objects at the organisation  and later user level which reorder and hide custom fields or hide them conditionally

My preference is for the third option as this can extend to user preferences and is the lightest touch on existing functionality as all existing functionality is read only for custom fields.

In order to implement it then we have some actions:
A "hide" of a custom field is persisted either just to the user or to the organisation
This can be a set of checkboxes with the options 
visible to all with access
hidden for organisation
visible only to project editors

Later it can also include hidden for me

For reorders then these would also be stored at the organisation level
Owners of the organisation would have a button "set fields to defaults" which would put the order back


User Profiles
------------------------------
Personal details (if webauth or user creation details not quite correct) - need to ensure that webauth does not re-update the personal details if this happens
Need to ensure that webauth does not update first name and last name unless they are blank
Change email - external collab 
Leave system

**Comment by KarenPorter** [comment]
used in discussion to define scope then relevant constituent pieces of work each had a list item created for it and scheduled as appropriate - therefore closing this issue as done
