### ISSUE TITLE
Disable / fix export data summary

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#785]
export data summary is currently broken and takes you to a nasty looking error page.

**Comment by PaulBarrett79** [comment]
I've disabled this for now - there is something going on with permissions checking that I don't understand - authorization.py line 115 is trying to check a variable before assignment, also I don't understand what it is doing - there is no data available to loop through.

In the background (and now unused) I've added the same check as for the edit mode - "Is only 1 project selected" so that this link would not show up if either 0 or 2+ projects are selected.

Additionally, I don't think the results table is the best place to have this - it should now be part of the project list. It used to be available on the compound list when that was part of the compound page, which is why it made sense. Having to check that there is only one project selected means this functionality will be not easily discoverable by the user - better to make it more obvious in the context of one project.

**Comment by KarenPorter** [comment]
@strets123 is this subsumed by #811 action to check for single project before allowing export?

**Comment by strets123** [comment]
Raised a new ticket #842 for this

**Comment by aekhendry** [comment]
Closing as now in 842
