### ISSUE TITLE
Ability to clear all search parameters with out clearing which projects you are searching through

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#807]
I would like to see the ability to clear all search parameters with the exception of the projects being looked at. 

I'm assuming the best way to do this will be to add another button that says 'clear search parameters' or something to that effect.

The reason is that when the search engine gets confused, it is very frustrating to have to find the project you were looking through again via the search page. It's going to be even more frustrating for people using this that don't realise the project criteria has been cleared and cannot understand why they are now not seeing any entries.

**Comment by KarenPorter** [comment]
In keeping with the existing search layout (which could do with a bit of tweaking in any case), I'd suggest an option to 'clear key search parameters' and one to 'clear advanced search parameters' so that users can clear out just relevant areas.  Key search parameters being the 3 at the top (all that remain when user hides advanced search).  What do you think @aekhendry @strets123 ?

**Comment by KarenPorter** [comment]
@aekhendry @strets123 still needs resolving - we don't have this functionality, so should we?

**Comment by aekhendry** [comment]
I think this is issue is better handled in the current set up. Demand is not high for this change and as such I'm closing it.
