### ISSUE TITLE
Ability to search for whole group of inventories via relevant tags

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#809]
For any group inventory it will be necessary to be able to quickly add this collection of projects to the search page. Currently you can only add one project at time, which will be impractical for large groups. I propose a tagging system, whereby a project can be tagged with a certain term (i.e. Chemistry Department Inventory). I can see a use case where being able to tag projects with certain terms will allow for a greater amount of search customisability that would be of genuine use to users with 2+ projects

**Comment by strets123** [comment]
In the first instance, will users have acess to things OTHER than the projects the set on inventories they want to search? If so there is no need for this feature as they will see information in all projects by default.

Otherwise, would it not be simpler to split data into two tabs - "projects i contribute to" vs "projects I have access to"

**Comment by KarenPorter** [comment]
@aekhendry I think this was suggested before the effort to save searches was scheduled .  That effort makes this request redundant to some extent I believe.  Can you please confirm if there is still a use case for this and say what sort of priority you'd assign - ie is it a contender for scheduling in Feb?

**Comment by KarenPorter** [comment]
Resolved. Closing
