### ISSUE TITLE
Excel/SDF export missing mapped custom fields

### ISSUE THREAD

**Issue by ddamerell53** [thesgc/chembiohub_helpdesk#812]
The SGC installation of ChemReg includes the two custom fields: SGCGlobalID and SGCLocalID.  When we batch upload an SDF the corresponding attributes get mapped to the correct custom fields.  However when we export to Excel these fields are missing.  We must export to Excel/SDF for audit purposes for all registration requests so it's important to have these fields present in the export.

**Comment by strets123** [comment]
This is actually a feature and a repair to a previous "bug" a bug. The user needs to have a project selected in order to see the fields in the export. Previously there was a complaint that there were too many irrelevant fields if you do a multi project export and this was seen as a "quick fix" thoughts @aekhendry @KarenPorter @ddamerell53 @PaulBarrett79

**Comment by KarenPorter** [comment]
Could add an 'include custom fields' option to the export which is non-selectable if >1 project?

**Comment by strets123** [comment]
I have now disabled export unless only a single project is selected and put a note to that effect in the info box

**Comment by KarenPorter** [comment]
and enabled export of custom fields for given project? @strets123 

Can you please assign issue to correct card list.

**Comment by aekhendry** [comment]
Working as described. hubtest chrome
