### ISSUE TITLE
Export as excel is exporting a bunch of headings that don't exist in project

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#945]
If I export as XLSX from demo ChemReg project I get a bunch of fields that dont exist. note that as you go across the table, everything is fine until you reach the system generated columns on the right hand side. Then it starts injecting incorrect fields.

**Comment by aekhendry** [comment]
This does not seem to happen with other new projects which export fine.

**Comment by strets123** [comment]
Began work on this by implementing the new schema in #947

**Comment by KarenPorter** [comment]
fixed awaining testing

**Comment by KarenPorter** [comment]
Exported multiple projects successfully.

Exported single project successfully.

One defect seen consistently.  Project Hendry Compounds (/demo) columns export in a slightly different order (CAS number and Comments fields are move to the right compared to order within ChemiReg.

**Comment by PaulBarrett79** [comment]
Estimate this is a 1 hour job

**Comment by strets123** [comment]
This is actually quite hard to fix for the amount of value.

I have built the schema list of fields on the back end across all the fields the user has access to.

Therefore file uploads come first in the hendry compounds project

because you have access to them in another project.

I didn't think of this when I created the system

If we think about it from the user's perspective at least it means that fields juggle less in their ordering, although I admit it is annoying.

@aekhendry how many users do you have with radically different structures between projects but some shared fields?

**Comment by strets123** [comment]
Alsoi SMILES and inchi and other chemical columns not present

**Comment by strets123** [comment]
This can be fixed by changing the way the field order is built up but it will actually be a bit tricky to do it without a lag

**Comment by strets123** [comment]
estimate is to fix the smiles issue

**Comment by strets123** [comment]
Chemical fields have now been added. @PaulBarrett79  this functionality requires a full reindex

**Comment by KarenPorter** [comment]
@strets123 this is in testing column but your comment looks like it needs action before it can be tested.  What is the status?

**Comment by KarenPorter** [comment]
Tested and passed.
