### ISSUE TITLE
Filter - pick from list non-intuitive

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#973]
I select CBH_ID to filter on and paste in an existing ID, I get the option to pick that existing value or 'create new' - no ide what that is supposed to do.

**Comment by strets123** [comment]
I have fixed these issues, now works as expected - no duplicates, able to add new items only when adding data to a field allowing create, not usually able to add items

**Comment by KarenPorter** [comment]
Fixed issue as reported.  However, testing ability to add items shows a non-intuitive behaviour.

I've set owner in Hendry compounds to be choice allowing create.  Testing in addsingle page, I type in a new option and select it (create new), but the drop down stays open which I think is confusing.  If I click on my choice again it is unselected and my choice is removed. I know this is by design but think it could be improved.  Not high priority.

**Comment by PaulBarrett79** [comment]
Low priority but I think this would only be a couple of hours work

**Comment by PaulBarrett79** [comment]
After analysis of this, both Andy and I feel this functionality works well enough. We think it should remain as it is, given to users to evaluate for themselves and get a broad spectrum of opinion.

The "create" a choice functionality makes sense in that if the user adds a new value, they are extremely likely to use that value rather than the ones provided. That value can only hang around if it is used as the selected value. Otherwise, lots of choices could be created, not used, added to the list of possibilities and potentially damage data integrity. It would also give perceived false negatives in search results.

Since issue has been fixed and verified, moving this to awaiting testing

**Comment by KarenPorter** [comment]
Accept this should go as is in front of users for wider commentary on whether it is an issue and how it might be improved.
